# Generated by Django 4.2.28 on 2026-03-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_attendance_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyattendance',
            name='attendance_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokenreward',
            name='reward_date_idx',
        ),
        migrations.AddField(
            model_name='tokenredemption',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tokenreward',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tokenreward',
            name='barcode_generated',
            field=models.BooleanField(default=False),
        ),
    ]
